### ISSUE TITLE
Won't work with kafka 1.0.0

### ISSUE THREAD

**Issue by lohmag** [myfitnesspal/kafka-statsd-reporter#5]
Hello. 
This package builds to:
kafka-statsd-reporter-1.0.0.jar
kafka-statsd-reporter-1.0.0-javadoc.jar
kafka-statsd-reporter-1.0.0-sources.jar
kafka-statsd-reporter-1.0.0-uber.jar

I tryed slim and fat versions in first place kafka says:

`waiting for kafka to be ready
[2018-01-22 10:42:04,419] FATAL  (kafka.Kafka$)
java.lang.ClassNotFoundException: com/myfitnesspal/kafka/KafkaStatsdMetricsReporter[
   at java.lang.Class.forName0(Native Method)
   at java.lang.Class.forName(Class.java:348)
   at kafka.utils.CoreUtils$.createObject(CoreUtils.scala:179)
   at kafka.metrics.KafkaMetricsReporter$.$anonfun$startReporters$1(KafkaMetricsReporter.scala:65)
   at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
   at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
   at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
   at kafka.metrics.KafkaMetricsReporter$.startReporters(KafkaMetricsReporter.scala:64)
   at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:27)
   at kafka.Kafka$.main(Kafka.scala:82)
   at kafka.Kafka.main(Kafka.scala)
`

With kafka-statsd-reporter-1.0.0-uber.jar :

`waiting for kafka to be ready
Exception in thread "main" java.lang.NoSuchMethodError: kafka.utils.Logging.$init$(Lkafka/utils/Logging;)V
   at kafka.Kafka$.<init>(Kafka.scala:32)
   at kafka.Kafka$.<clinit>(Kafka.scala)
   at kafka.Kafka.main(Kafka.scala)
`

Is this reporter still working?

**Comment by ralph-tice** [comment]
I don't have commit bit here anymore, but you can see from https://github.com/myfitnesspal/kafka-statsd-reporter/blob/master/pom.xml#L21 that this hasn't been updated since 0.8.2.1
